import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <ThemeProvider>
          <header className="sticky top-0 z-40 w-full border-b border-black/10 dark:border-white/10 backdrop-blur bg-background/70">
            <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
              <a href="#hero" className="font-semibold tracking-tight">My Portfolio</a>
              <nav className="hidden sm:flex items-center gap-4 text-sm">
                <a href="#about" className="hover:underline underline-offset-4">About</a>
                <a href="#skills" className="hover:underline underline-offset-4">Skills</a>
                <a href="#projects" className="hover:underline underline-offset-4">Projects</a>
                <a href="#contact" className="hover:underline underline-offset-4">Contact</a>
              </nav>
              <ThemeToggle />
            </div>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
